remote_theme: pages-themes/modernist@v0.2.0
plugins:
  - jekyll-default-layout
show_downloads: false
title: API Rehab
description: A performance extravaganza
github:
  is_project_page: true
  repository_url: https://github.com/RiccardoGMoschetti/API-rehab
theme: just-the-docs
url: https://api.rehab
aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://github.com/YOUR-USERNAME/YOUR-SITE-NAME
